name: type-check
on: [push, pull_request]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install -e .[dev]
      - run: mypy omndx/agents/llm_local.py omndx/agents/core_agent.py
